# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-01 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import os
import datetime
import csv as csv

def load_superuser(apps, schema_editor):

    User = apps.get_model("auth", "User")
    user = User()
    user.username = "06337"
    user.first_name = "Edwin Alberto Velasco"
    user.email = "edwinalbertovelasco8@gmail.com"
    #user.set_password('Claro"##0')
    user.password = "pbkdf2_sha256$24000$M2GCizhOGfsG$xtPlLQIl+Bp74MXppeO8uXaOR9Rj/4XRyrISZZgejTs="
    user.is_superuser = True
    user.is_staff = True
    user.save()

    Persona = apps.get_model("Diseraca", "Persona")
    p = Persona()
    p.user = user
    p.tipo = 2
    p.save()


def load_turnos_iniciales(apps, schema_editor):

    Turno = apps.get_model("Diseraca", "Turno")
    base_dir_doc = os.getcwd()
    data = csv.reader(open(base_dir_doc + "/turnos_inicio.csv", mode="rw"))
    for time_start, time_end, dia, estado in data:
        turno = Turno()
        turno.time_start = datetime.time(hour=int(time_start), minute=0, second=0)
        turno.time_end = datetime.time(hour=int(time_end), minute=0, second=0)
        turno.dia = int(dia)
        turno.estado = 0
        turno.save()



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=0)),
                ('date_turno', models.DateField()),
                ('datetime_registro', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=12)),
                ('cc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Beca_Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Beca')),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=45)),
                ('grupo', models.CharField(max_length=1)),
                ('matriculados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ip_Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('estado', models.BooleanField(choices=[(True, b'Activar'), (False, b'Desactivar')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, b'Profesor'), (1, b'Beca'), (2, b'Admin')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, null=True)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('grupo', models.CharField(max_length=1, null=True)),
                ('matriculados', models.IntegerField()),
                ('date_prestamo', models.DateTimeField(auto_now=True)),
                ('date_turno', models.DateField()),
                ('ip', models.GenericIPAddressField()),
                ('usuario', models.CharField(max_length=50)),
                ('estado', models.IntegerField(choices=[(0, b'Activo'), (1, b'Entregado'), (2, b'Cancelado'), (3, b'Anulado')], default=0)),
                ('tipo', models.IntegerField(choices=[(0, b'Activo'), (1, b'Entregado'), (2, b'Cancelado'), (3, b'Anulado')], default=0)),
                ('solicitante', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=12, null=True)),
                ('detalle', models.CharField(max_length=50, null=True)),
                ('beca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Beca')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Departamento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[(0, b'Sala de clase'), (1, b'Aula virtual'), (2, b'Auditorio')], default=0)),
                ('estado', models.IntegerField(choices=[(0, b'Activo'), (1, b'Mantenimiento'), (2, b'Fuera de servicio')], default=0)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('motivo', models.TextField()),
                ('responsable', models.CharField(max_length=40)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('dia', models.IntegerField(choices=[(0, b'Lunes'), (1, b'Martes'), (2, b'Miercoles'), (3, b'Jueves'), (4, b'Viernes'), (5, b'Sabado')])),
                ('estado', models.IntegerField(choices=[(0, b'Activado'), (1, b'Desactivado')], default=0, help_text=b'activo --> 0, desactivado --> 1')),
            ],
        ),
        migrations.CreateModel(
            name='Turno_Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, b'Activado'), (1, b'Desactivado'), (2, b'Temporal')], default=0)),
                ('hasta', models.DateField(blank=True, help_text=b'hasta cuando se desactivara el turno', null=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Sala')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Turno')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Profesor'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='turno_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Turno_Sala'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Departamento'),
        ),
        migrations.AddField(
            model_name='carga',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Carrera'),
        ),
        migrations.AddField(
            model_name='carga',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Profesor'),
        ),
        migrations.AddField(
            model_name='beca_turno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Turno'),
        ),
        migrations.AddField(
            model_name='beca',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Persona'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='beca_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Beca_Turno'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diseraca.Ip_Registro'),
        ),
        migrations.RunPython(load_superuser),
        migrations.RunPython(load_turnos_iniciales),
    ]
