# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-17 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diseraca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca_turno',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='beca_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Diseraca.Beca_Turno'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Diseraca.Ip_Registro'),
        ),
        migrations.AlterField(
            model_name='beca_turno',
            name='beca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Diseraca.Beca'),
        ),
        migrations.AlterField(
            model_name='beca_turno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Diseraca.Turno'),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Diseraca.Profesor'),
        ),
    ]
