# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-18 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diseraca', '0002_auto_20180217_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set([('beca_turno', 'date_turno')]),
        ),
        migrations.AlterUniqueTogether(
            name='beca_turno',
            unique_together=set([('beca', 'turno')]),
        ),
    ]
