# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diseraca', '0003_prestamo_matriculados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='date_end',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='semestre',
            old_name='date_start',
            new_name='fecha_inicio',
        ),
        migrations.AlterField(
            model_name='semestre',
            name='nombre',
            field=models.TextField(max_length=10),
        ),
    ]
