# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-02 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diseraca', '0003_auto_20180218_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beca_turno',
            options={'verbose_name': 'Turno de beca', 'verbose_name_plural': 'Turnos de beca'},
        ),
    ]
