# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diseraca', '0004_auto_20180302_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno_sala',
            name='desde',
            field=models.DateField(blank=True, help_text=b'desde cuando se desactivara el turno', null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Diseraca.Carrera'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.IntegerField(choices=[(0, b'Audiovisuales'), (1, b'Aula virtual'), (2, b'Auditorio')], default=0),
        ),
    ]
